// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/athenz/agent/api/message/v1/athenz_agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessStatus int32

const (
	AccessStatus_ALLOW                   AccessStatus = 0
	AccessStatus_DENY                    AccessStatus = 1
	AccessStatus_DENY_ROLE_TOKEN_EXPIRED AccessStatus = 2
	AccessStatus_DENY_ROLE_TOKEN_INVALID AccessStatus = 3
	AccessStatus_DENY_INVALID_PARAMETERS AccessStatus = 4
	AccessStatus_DENY_DOMAIN_MISMATCH    AccessStatus = 5
	AccessStatus_DENY_DOMAIN_NOT_FOUND   AccessStatus = 6
	AccessStatus_DENY_NO_MATCH           AccessStatus = 7
	AccessStatus_DENY_DOMAIN_EMPTY       AccessStatus = 8
	AccessStatus_DENY_DOMAIN_EXPIRED     AccessStatus = 9
)

// Enum value maps for AccessStatus.
var (
	AccessStatus_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
		2: "DENY_ROLE_TOKEN_EXPIRED",
		3: "DENY_ROLE_TOKEN_INVALID",
		4: "DENY_INVALID_PARAMETERS",
		5: "DENY_DOMAIN_MISMATCH",
		6: "DENY_DOMAIN_NOT_FOUND",
		7: "DENY_NO_MATCH",
		8: "DENY_DOMAIN_EMPTY",
		9: "DENY_DOMAIN_EXPIRED",
	}
	AccessStatus_value = map[string]int32{
		"ALLOW":                   0,
		"DENY":                    1,
		"DENY_ROLE_TOKEN_EXPIRED": 2,
		"DENY_ROLE_TOKEN_INVALID": 3,
		"DENY_INVALID_PARAMETERS": 4,
		"DENY_DOMAIN_MISMATCH":    5,
		"DENY_DOMAIN_NOT_FOUND":   6,
		"DENY_NO_MATCH":           7,
		"DENY_DOMAIN_EMPTY":       8,
		"DENY_DOMAIN_EXPIRED":     9,
	}
)

func (x AccessStatus) Enum() *AccessStatus {
	p := new(AccessStatus)
	*p = x
	return p
}

func (x AccessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_athenz_agent_api_message_v1_athenz_agent_proto_enumTypes[0].Descriptor()
}

func (AccessStatus) Type() protoreflect.EnumType {
	return &file_proto_athenz_agent_api_message_v1_athenz_agent_proto_enumTypes[0]
}

func (x AccessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessStatus.Descriptor instead.
func (AccessStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescGZIP(), []int{0}
}

type AccessCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Access   string `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`
	Resource string `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *AccessCheckRequest) Reset() {
	*x = AccessCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckRequest) ProtoMessage() {}

func (x *AccessCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckRequest.ProtoReflect.Descriptor instead.
func (*AccessCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AccessCheckRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccessCheckRequest) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *AccessCheckRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type AccessCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessCheckStatus AccessStatus `protobuf:"varint,1,opt,name=access_check_status,json=accessCheckStatus,proto3,enum=athenz.agent.api.message.v1.AccessStatus" json:"access_check_status,omitempty"`
}

func (x *AccessCheckResponse) Reset() {
	*x = AccessCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckResponse) ProtoMessage() {}

func (x *AccessCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckResponse.ProtoReflect.Descriptor instead.
func (*AccessCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AccessCheckResponse) GetAccessCheckStatus() AccessStatus {
	if x != nil {
		return x.AccessCheckStatus
	}
	return AccessStatus_ALLOW
}

type ServiceTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceTokenRequest) Reset() {
	*x = ServiceTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTokenRequest) ProtoMessage() {}

func (x *ServiceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTokenRequest.ProtoReflect.Descriptor instead.
func (*ServiceTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescGZIP(), []int{2}
}

type ServiceTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ServiceTokenResponse) Reset() {
	*x = ServiceTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTokenResponse) ProtoMessage() {}

func (x *ServiceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTokenResponse.ProtoReflect.Descriptor instead.
func (*ServiceTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_athenz_agent_api_message_v1_athenz_agent_proto protoreflect.FileDescriptor

var file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDesc = []byte{
	0x0a, 0x34, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x7a, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x7a, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x7a, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0x5e, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0x70, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x13, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x7a,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x11, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x14,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0xf2, 0x01, 0x0a, 0x0c, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x41,
	0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x01,
	0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45, 0x4e, 0x59, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x54, 0x4f,
	0x4b, 0x45, 0x4e, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1b, 0x0a,
	0x17, 0x44, 0x45, 0x4e, 0x59, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45,
	0x4e, 0x59, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d,
	0x45, 0x54, 0x45, 0x52, 0x53, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x45, 0x4e, 0x59, 0x5f,
	0x44, 0x4f, 0x4d, 0x41, 0x49, 0x4e, 0x5f, 0x4d, 0x49, 0x53, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10,
	0x05, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x45, 0x4e, 0x59, 0x5f, 0x44, 0x4f, 0x4d, 0x41, 0x49, 0x4e,
	0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d,
	0x44, 0x45, 0x4e, 0x59, 0x5f, 0x4e, 0x4f, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x07, 0x12,
	0x15, 0x0a, 0x11, 0x44, 0x45, 0x4e, 0x59, 0x5f, 0x44, 0x4f, 0x4d, 0x41, 0x49, 0x4e, 0x5f, 0x45,
	0x4d, 0x50, 0x54, 0x59, 0x10, 0x08, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x45, 0x4e, 0x59, 0x5f, 0x44,
	0x4f, 0x4d, 0x41, 0x49, 0x4e, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x09, 0x42,
	0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x61,
	0x6d, 0x65, 0x64, 0x2d, 0x79, 0x6f, 0x75, 0x73, 0x65, 0x66, 0x69, 0x2f, 0x61, 0x74, 0x68, 0x65,
	0x6e, 0x7a, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x2e, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescOnce sync.Once
	file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescData = file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDesc
)

func file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescGZIP() []byte {
	file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescOnce.Do(func() {
		file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescData)
	})
	return file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDescData
}

var file_proto_athenz_agent_api_message_v1_athenz_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_athenz_agent_api_message_v1_athenz_agent_proto_goTypes = []interface{}{
	(AccessStatus)(0),            // 0: athenz.agent.api.message.v1.AccessStatus
	(*AccessCheckRequest)(nil),   // 1: athenz.agent.api.message.v1.AccessCheckRequest
	(*AccessCheckResponse)(nil),  // 2: athenz.agent.api.message.v1.AccessCheckResponse
	(*ServiceTokenRequest)(nil),  // 3: athenz.agent.api.message.v1.ServiceTokenRequest
	(*ServiceTokenResponse)(nil), // 4: athenz.agent.api.message.v1.ServiceTokenResponse
}
var file_proto_athenz_agent_api_message_v1_athenz_agent_proto_depIdxs = []int32{
	0, // 0: athenz.agent.api.message.v1.AccessCheckResponse.access_check_status:type_name -> athenz.agent.api.message.v1.AccessStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_athenz_agent_api_message_v1_athenz_agent_proto_init() }
func file_proto_athenz_agent_api_message_v1_athenz_agent_proto_init() {
	if File_proto_athenz_agent_api_message_v1_athenz_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_athenz_agent_api_message_v1_athenz_agent_proto_goTypes,
		DependencyIndexes: file_proto_athenz_agent_api_message_v1_athenz_agent_proto_depIdxs,
		EnumInfos:         file_proto_athenz_agent_api_message_v1_athenz_agent_proto_enumTypes,
		MessageInfos:      file_proto_athenz_agent_api_message_v1_athenz_agent_proto_msgTypes,
	}.Build()
	File_proto_athenz_agent_api_message_v1_athenz_agent_proto = out.File
	file_proto_athenz_agent_api_message_v1_athenz_agent_proto_rawDesc = nil
	file_proto_athenz_agent_api_message_v1_athenz_agent_proto_goTypes = nil
	file_proto_athenz_agent_api_message_v1_athenz_agent_proto_depIdxs = nil
}
